-- ============================================================
-- Portfolio Leween / Tremble — Backend Supabase
-- À exécuter UNE FOIS dans Supabase > SQL Editor.
--
-- IMPORTANT :
-- 1) Créez d'abord votre utilisateur dans Authentication > Users.
-- 2) Copiez son UUID.
-- 3) Remplacez VOTRE_UUID_ADMIN tout en bas de ce fichier.
-- 4) Exécutez tout le script.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1. Tables
-- ------------------------------------------------------------
create table if not exists public.site_settings (
    id text primary key,
    content_initialized boolean not null default false,
    updated_at timestamptz not null default now()
);

insert into public.site_settings (id, content_initialized)
values ('main', false)
on conflict (id) do nothing;

create table if not exists public.site_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

create table if not exists public.subjects (
    id text primary key,
    name text not null,
    icon text not null default 'fa-solid fa-book',
    sort_order integer not null default 0,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.documents (
    id bigint generated by default as identity primary key,
    subject_id text not null references public.subjects(id) on update cascade on delete restrict,
    type text not null check (type in ('lessons', 'exercises', 'sheets')),
    title text not null,
    url text not null,
    storage_path text,
    file_name text,
    sort_order integer not null default 0,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.info_blocks (
    id bigint generated by default as identity primary key,
    title text not null,
    text text not null,
    icon text not null default 'fa-solid fa-circle-info',
    image_url text,
    image_storage_path text,
    sort_order integer not null default 0,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text not null default '',
    icon text not null default 'fa-solid fa-laptop-code',
    category text not null default 'application' check (category in ('application', 'tool', 'game')),
    status text not null default 'development' check (status in ('development', 'available', 'prototype', 'archived')),
    tags text[] not null default '{}',
    features text[] not null default '{}',
    logo_url text,
    logo_storage_path text,
    app_url text,
    dev_url text,
    sort_order integer not null default 0,
    is_published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists documents_subject_idx on public.documents(subject_id);
create index if not exists documents_sort_idx on public.documents(subject_id, type, sort_order);
create index if not exists projects_sort_idx on public.projects(sort_order);
create index if not exists info_blocks_sort_idx on public.info_blocks(sort_order);

-- ------------------------------------------------------------
-- 2. Mise à jour automatique de updated_at
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_subjects_updated_at on public.subjects;
create trigger trg_subjects_updated_at before update on public.subjects
for each row execute function public.set_updated_at();

drop trigger if exists trg_documents_updated_at on public.documents;
create trigger trg_documents_updated_at before update on public.documents
for each row execute function public.set_updated_at();

drop trigger if exists trg_info_blocks_updated_at on public.info_blocks;
create trigger trg_info_blocks_updated_at before update on public.info_blocks
for each row execute function public.set_updated_at();

drop trigger if exists trg_projects_updated_at on public.projects;
create trigger trg_projects_updated_at before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists trg_site_settings_updated_at on public.site_settings;
create trigger trg_site_settings_updated_at before update on public.site_settings
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 3. Rôle administrateur
-- ------------------------------------------------------------
create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.site_admins
        where user_id = auth.uid()
    );
$$;

grant execute on function public.is_site_admin() to anon, authenticated;

-- ------------------------------------------------------------
-- 4. Row Level Security
-- ------------------------------------------------------------
alter table public.site_settings enable row level security;
alter table public.site_admins enable row level security;
alter table public.subjects enable row level security;
alter table public.documents enable row level security;
alter table public.info_blocks enable row level security;
alter table public.projects enable row level security;

-- Settings
drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "Admin can update site settings" on public.site_settings;
create policy "Admin can update site settings"
on public.site_settings for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

-- Admins : un utilisateur authentifié ne peut voir que sa propre ligne.
drop policy if exists "Admin can read own membership" on public.site_admins;
create policy "Admin can read own membership"
on public.site_admins for select
to authenticated
using (user_id = auth.uid());

-- Subjects
drop policy if exists "Public can read published subjects" on public.subjects;
create policy "Public can read published subjects"
on public.subjects for select
to anon, authenticated
using (is_published or public.is_site_admin());

drop policy if exists "Admin can insert subjects" on public.subjects;
create policy "Admin can insert subjects"
on public.subjects for insert
to authenticated
with check (public.is_site_admin());

drop policy if exists "Admin can update subjects" on public.subjects;
create policy "Admin can update subjects"
on public.subjects for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "Admin can delete subjects" on public.subjects;
create policy "Admin can delete subjects"
on public.subjects for delete
to authenticated
using (public.is_site_admin());

-- Documents
drop policy if exists "Public can read published documents" on public.documents;
create policy "Public can read published documents"
on public.documents for select
to anon, authenticated
using (
    public.is_site_admin()
    or (
        is_published
        and exists (
            select 1 from public.subjects s
            where s.id = documents.subject_id and s.is_published
        )
    )
);

drop policy if exists "Admin can insert documents" on public.documents;
create policy "Admin can insert documents"
on public.documents for insert
to authenticated
with check (public.is_site_admin());

drop policy if exists "Admin can update documents" on public.documents;
create policy "Admin can update documents"
on public.documents for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "Admin can delete documents" on public.documents;
create policy "Admin can delete documents"
on public.documents for delete
to authenticated
using (public.is_site_admin());

-- Informations
drop policy if exists "Public can read published info" on public.info_blocks;
create policy "Public can read published info"
on public.info_blocks for select
to anon, authenticated
using (is_published or public.is_site_admin());

drop policy if exists "Admin can insert info" on public.info_blocks;
create policy "Admin can insert info"
on public.info_blocks for insert
to authenticated
with check (public.is_site_admin());

drop policy if exists "Admin can update info" on public.info_blocks;
create policy "Admin can update info"
on public.info_blocks for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "Admin can delete info" on public.info_blocks;
create policy "Admin can delete info"
on public.info_blocks for delete
to authenticated
using (public.is_site_admin());

-- Projects
drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects"
on public.projects for select
to anon, authenticated
using (is_published or public.is_site_admin());

drop policy if exists "Admin can insert projects" on public.projects;
create policy "Admin can insert projects"
on public.projects for insert
to authenticated
with check (public.is_site_admin());

drop policy if exists "Admin can update projects" on public.projects;
create policy "Admin can update projects"
on public.projects for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "Admin can delete projects" on public.projects;
create policy "Admin can delete projects"
on public.projects for delete
to authenticated
using (public.is_site_admin());

-- ------------------------------------------------------------
-- 5. Storage
-- ------------------------------------------------------------
-- 50 Mo par fichier pour les documents.
insert into storage.buckets (id, name, public, file_size_limit)
values ('course-files', 'course-files', true, 52428800)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

-- 10 Mo par image/logo.
insert into storage.buckets (id, name, public, file_size_limit)
values ('site-assets', 'site-assets', true, 10485760)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

-- Lecture publique des fichiers
drop policy if exists "Public can read course files" on storage.objects;
create policy "Public can read course files"
on storage.objects for select
to public
using (bucket_id = 'course-files');

drop policy if exists "Public can read site assets" on storage.objects;
create policy "Public can read site assets"
on storage.objects for select
to public
using (bucket_id = 'site-assets');

-- Écriture réservée à l'administrateur
drop policy if exists "Admin can upload course files" on storage.objects;
create policy "Admin can upload course files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'course-files' and public.is_site_admin());

drop policy if exists "Admin can update course files" on storage.objects;
create policy "Admin can update course files"
on storage.objects for update
to authenticated
using (bucket_id = 'course-files' and public.is_site_admin())
with check (bucket_id = 'course-files' and public.is_site_admin());

drop policy if exists "Admin can delete course files" on storage.objects;
create policy "Admin can delete course files"
on storage.objects for delete
to authenticated
using (bucket_id = 'course-files' and public.is_site_admin());

drop policy if exists "Admin can upload site assets" on storage.objects;
create policy "Admin can upload site assets"
on storage.objects for insert
to authenticated
with check (bucket_id = 'site-assets' and public.is_site_admin());

drop policy if exists "Admin can update site assets" on storage.objects;
create policy "Admin can update site assets"
on storage.objects for update
to authenticated
using (bucket_id = 'site-assets' and public.is_site_admin())
with check (bucket_id = 'site-assets' and public.is_site_admin());

drop policy if exists "Admin can delete site assets" on storage.objects;
create policy "Admin can delete site assets"
on storage.objects for delete
to authenticated
using (bucket_id = 'site-assets' and public.is_site_admin());

commit;

-- ============================================================
-- 6. À MODIFIER AVANT D'EXÉCUTER CETTE DERNIÈRE LIGNE
-- ============================================================
-- Remplacez VOTRE_UUID_ADMIN par l'UUID du compte créé dans
-- Authentication > Users, puis exécutez la ligne ci-dessous.
-- Exemple : 12345678-abcd-1234-abcd-1234567890ab

do $$
declare
    admin_uuid_text text := 'VOTRE_UUID_ADMIN';
begin
    if admin_uuid_text = 'VOTRE_UUID_ADMIN' then
        raise notice 'Compte admin non ajouté : remplacez VOTRE_UUID_ADMIN puis réexécutez ce bloc.';
    else
        insert into public.site_admins (user_id)
        values (admin_uuid_text::uuid)
        on conflict (user_id) do nothing;
    end if;
end $$;
